main: fr.skytryx.ultihc.Main
name: UltiHC
version: 0.0.0
description: UHC Hosting Plugin
author: SkyTryX
commands:
  inspectmap:
    description: A command to inspect the uhc map
  reloadmap:
    description: A command to reload the uhc map
  stats:
    descritpion: A command to look at someone's stats
